// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VesselManagementSystemAPI.Data;

#nullable disable

namespace VesselManagementSystemAPI.Migrations
{
    [DbContext(typeof(VesselDbContext))]
    [Migration("20250512134931_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VesselManagementSystemAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ShipId")
                        .HasColumnType("int");

                    b.Property<int>("ShipTonnage")
                        .HasColumnType("int");

                    b.Property<string>("ShipType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ShipId")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("VesselManagementSystemAPI.Models.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("VesselManagementSystemAPI.Models.Ship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImoNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("VesselManagementSystemAPI.Models.ShipOwner", b =>
                {
                    b.Property<int>("ShipId")
                        .HasColumnType("int");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("ShipId", "OwnerId");

                    b.HasIndex("OwnerId");

                    b.ToTable("ShipOwners");
                });

            modelBuilder.Entity("VesselManagementSystemAPI.Models.Category", b =>
                {
                    b.HasOne("VesselManagementSystemAPI.Models.Ship", "Ship")
                        .WithOne("Category")
                        .HasForeignKey("VesselManagementSystemAPI.Models.Category", "ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("VesselManagementSystemAPI.Models.ShipOwner", b =>
                {
                    b.HasOne("VesselManagementSystemAPI.Models.Owner", "Owner")
                        .WithMany("ShipOwners")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VesselManagementSystemAPI.Models.Ship", "Ship")
                        .WithMany("ShipOwners")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("VesselManagementSystemAPI.Models.Owner", b =>
                {
                    b.Navigation("ShipOwners");
                });

            modelBuilder.Entity("VesselManagementSystemAPI.Models.Ship", b =>
                {
                    b.Navigation("Category")
                        .IsRequired();

                    b.Navigation("ShipOwners");
                });
#pragma warning restore 612, 618
        }
    }
}
